### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Ispirett**
Thanks for your time!!

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, nice try on your first bootstrap project. Here are few updates you need to make:
 - Project is too much dependent on `!important`, try to remove these from CSS.
 - Fix design [here](https://snag.gy/IDy81V.jpg), [here](https://snag.gy/wJifNc.jpg), [here](https://snag.gy/HGs1QW.jpg), [here](https://snag.gy/S9E73C.jpg) and [here](https://snag.gy/FXO8kj.jpg)
 - Navbar not showing when on small screen
 - Project is to use bootstrap but it's still mostly dependent on custom CSS, you can check utility classes as well [here](https://getbootstrap.com/docs/4.3/utilities/borders/).

Feel free to reach me on slack. Once updated, kindly submit for review.

**Review by inhaq — CHANGES_REQUESTED** [review]
Hi, good work on fixes. [Navbar](https://snag.gy/hVf87s.jpg) shouldn't go to two lines instead it should shrink it size to remain on the same line. [Here](https://snag.gy/hwBeko.jpg) minor fix to text required. These minor fixes and you'll be good to go to the next project. 
Once updated, kindly submit for review.

**Comment by Ispirett** [comment]
Ok thanks missed those

**Review by inhaq — APPROVED** [review]
### Perfect 💯
You've done an amazing job. Go ahead and submit a project completion form.
Good luck with the next project.👍🏻

**Comment by Ispirett** [comment]
Thanks !!!

**Pull request merged**
